modLoader="javafml"
loaderVersion="[47,)" # Para 1.20.1, el 47 es el m√≠nimo de Forge
license="MIT"

[[mods]]
modId="rustic"
version="0.0.1"
displayName="Rustic port"
description='''
Beautiful medieval stuff
'''