modLoader="javafml"
loaderVersion="[47,)" # Para 1.20.1, el 47 es el m√≠nimo de Forge
license="MIT"

[[mods]]
modId="mediccombatmod"
version="0.0.1"
displayName="Medic!"
description='''
Yelling it to your friend might help
'''